[SC-68972] Fix using temp view in Delta DML operations
after SPARK-33142, the SQL temp view and permanent view have the same behavior.
But this breaks some delta commands when a temp view is used. For example, after
SPARK-33142, below queries will fail
```sql
CREATE TEMP VIEW v AS SELECT * FROM tbl
DELETE FROM v WHERE key = 1
```
error:
```
AssertionError: assertion failed: No plan for DeleteFromTable
```
```sql
CREATE TEMP VIEW v AS SELECT * FROM tbl
UPDATE v SET key = 1
```
error:
```
UPDATE destination only supports Delta sources.
```

This PR will fix above usage.

Newly added tests

Author: Linhong Liu <linhong.liu@databricks.com>

GitOrigin-RevId: 76ecfba9155dc3c4aa20504852bfff93d490b083