[DELTA-OSS-EXTERNAL] Fix AnalysisException message for configureSparkSessionWithExtensionAndCatalog
This PR proposes to fix the `AnalysisException` message in `DeltaErrors.configureSparkSessionWithExtensionAndCatalog`.

Before:
```
org.apache.spark.sql.AnalysisException: This Delta operation requires the SparkSession to be configured with the
    DeltaSparkSessionExtension and the DeltaCatalog. Please set the necessary
    configurations when creating the SparkSession as shown below.

      SparkSession.builder()
        .option("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
        .option("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog"
        ...
        .build()
```
After fix:
```
org.apache.spark.sql.AnalysisException: This Delta operation requires the SparkSession to be configured with the
    DeltaSparkSessionExtension and the DeltaCatalog. Please set the necessary
    configurations when creating the SparkSession as shown below.

      SparkSession.builder()
        .option("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension")
        .option("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog")
        ...
        .build()
```

Closes delta-io/delta#512

Signed-off-by: liwensun <liwen.sun@databricks.com>

Author: Terry Kim <yuminkim@gmail.com>

#12645 is resolved by liwensun/o69e912w.

GitOrigin-RevId: e1924cd53d79296f889aa78f10ec9a1f7b809c3a