Make examples/scala compile -- detail() is available since v2.1
Signed-off-by: Slim Ouertani <ouertani@gmail.com>

## Description

This Pr makes `examples/scala` compile and run with `sbt compile` and `sbt run`. By default this error is raised

```
[info] compiling 6 Scala sources to /private/tmp/delta/examples/scala/target/scala-2.13/classes ...
[error] /private/tmp/delta/examples/scala/src/main/scala/example/Utilities.scala:67:16: value detail is not a member of io.delta.tables.DeltaTable
[error]     deltaTable.detail().show()
[error]                ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

This is tested by making sure that `sbt compile` and `sbt run` commands works are expected.

## Does this PR introduce _any_ user-facing changes?

No changes, this is part of the build of example dir.

Closes delta-io/delta#1489

Signed-off-by: Shixiong Zhu <zsxwing@gmail.com>
GitOrigin-RevId: 15b132c42b6728a24cd0011f0ce5bf7031cd1302