[Spark] Fix compile error on Spark master due to ParserInterface changes (#3294)
## Description
https://github.com/apache/spark/pull/46665 introduced a new
`parseScript` method in `ParserInterface`, which broke compilation
against Spark master:
```
[error] /home/runner/work/delta/delta/spark/src/main/scala/io/delta/sql/parser/DeltaSqlParser.scala:75:7: class DeltaSqlParser needs to be abstract.
[error] Missing implementation for member of trait ParserInterface:
[error]   def parseScript(sqlScriptText: String): org.apache.spark.sql.catalyst.parser.CompoundBody = ???
[error] class DeltaSqlParser(val delegate: ParserInterface) extends ParserInterface {
[error]       ^
[warn] 100 warnings found
[error] one error found
[error] (spark / Compile / compileIncremental) Compilation failed
```

This PR fixes the issue by shimming the `ParserInterface` since
`parseScript` is not available in Spark 3.5
## How was this patch tested?
Existing DeltaSqlParserSuite